name: SAST (OSV-Scanner-Container)

# Change "main" to your default branch if you use a different name, i.e. "master"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read
  # Required to create GitHub issues
  issues: write

jobs:
  scan-pr:
    if: github.event_name == 'pull_request'
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.3.3"

  scan-and-create-issues:
    name: Scan & Create Issues
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Scan container image for vulnerabilities
        uses: ./.github/actions/sast-osv-scanner-container
        with:
          image: alpine:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
