name: SAST (OWASP Dependency Check)

on: workflow_dispatch

permissions:
  contents: read
  issues: write

jobs:
  owasp-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: ./.github/actions/sast-owasp-dependency-check
        with:
          nvd-api-key: ${{ secrets.nvdApiKey }}
          pom-file: 'pom.xml'
          max-cvss-score: '8.5'
          format: 'JSON'
          github-token: ${{ secrets.GITHUB_TOKEN }}
