name: SAST (OSV-Scanner-Container)

# Change "main" to your default branch if you use a different name, i.e. "master"
on: workflow_dispatch

permissions:
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read
  # Required to create GitHub issues
  issues: write

jobs:
  scan-and-create-issues:
    name: Scan & Create Issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan container image for vulnerabilities
        uses: ./.github/actions/sast-osv-scanner-container
        with:
          image: alpine:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
